# mkdocs.yml 路径是相对于 docs 目录的，而不是 mkdocs.yml
site_name: LeftMidRight's notes


site_description: 笔记
site_author: 左宗右
site_url: https://leftmidright.cn
repo_url: https://github.com/LeftMidRight/leftmidright.github.io
repo_name: LeftMidRight/notes

copyright: Copyright &copy; LeftMidRight

theme:
  name: material
  language: zh
  custom_dir: overrides
  search_index_only: true
  logo: images/head.jpg
  favicon: images/notebook.png
  font: false
  # palette:
  #   primary: 'indigo'
  #   accent: 'pink'

  features:
  #- navigation.instant # 点击内部链接时，不用全部刷新页面
  - navigation.tracking # 在url中使用标题定位锚点
  - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
  #- navigation.tabs.sticky # 滚动是隐藏顶部nav，需要配合navigation.tabs使用
  #- navigation.sections # nav节点缩进
  # - navigation.expand # 不折叠左侧nav节点
  - navigation.indexes # 指定节点index pages ，跟instant不兼容
  #- toc.integrate # 右侧生产目录 
  # - toc.integrate #导航集成
  #- navigation.top # 一键回顶部
  #- header.autohide
  - search.share # 搜索分享
  - search.suggest # 搜索建议
  - search.highlight #搜索高亮



plugins:
    - search:
        lang:
            - en
            - ja
        separator: '[\s\-\.]+'
    - blog:
        blog_dir: blog
        post_dir: "{blog}/posts"
        #blog_toc: true
        archive: true
        categories: true
        pagination: true
        pagination_per_page: 10
        post_url_date_format: ""
        pagination_if_single_page: true


extra:
  generator: false

# 扩展
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - abbr
  - pymdownx.snippets
  - def_list
  - tables
  - pymdownx.tasklist:
      custom_checkbox: true
  - attr_list
  - md_in_html
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.caret #下划线
  - pymdownx.mark #文本高亮
  - pymdownx.tilde #删除线
  - pymdownx.arithmatex: #latex支持
      generic: true
  - toc: 
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/js/all.min.js


extra_css:
  - assets/stylesheets/extra.css
  - https://cdn.jsdelivr.net/npm/lxgw-wenkai-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-lite-webfont@1.1.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-tc-webfont@1.0.0/style.css
  # - https://cdn.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.1.0/style.css
nav:
    - 计算机理论: 
      - "计算机理论/index.md"

      - 计算机网络: 
        - "./计算机理论/计算机网络/index.md"
        - 1.计算机网络和因特网: "计算机理论/计算机网络/1.计算机网络和因特网.md"
        - 1.1.计算机网络和因特网题目: "计算机理论/计算机网络/1.计算机网络和因特网题目.md"
        - 2.应用层: "计算机理论/计算机网络/2.应用层.md"
        - 3.运输层: "计算机理论/计算机网络/3.运输层.md"
      
      - 数据库: 
        - "计算机理论/数据库/index.md"
        - 概述: "计算机理论/数据库/0.概述.md"
      

    
    
    - 算法题单:
      - "./算法题/index.md"
      - 代码随想录:
        - "./算法题/代码随想录/index.md"
        - 数组: "./算法题/代码随想录/数组.md"
        - 链表: "./算法题/代码随想录/链表.md"
        - 哈希表: "./算法题/代码随想录/哈希表.md"
        - 字符串: "./算法题/代码随想录/字符串.md"
        - 栈与队列: "./算法题/代码随想录/栈与队列.md"

    - 博客:
      - "blog/index.md"